export interface CouncilMember {
  id: number;
  name: string;
  nameFa: string;
  title: string;
  titleFa: string;
  emoji: string;
  color: string;
  expertise: string;
  question_focus: string;
  personality: string;
  voice_style: string; // how they phrase things
}

export const councilMembers: CouncilMember[] = [
  {
    id: 1,
    name: "Leonardo da Vinci",
    nameFa: "لئوناردو داوینچی",
    title: "Artist & Renaissance Inventor",
    titleFa: "هنرمند و مخترع رنسانس",
    emoji: "🎨",
    color: "from-amber-500 to-yellow-600",
    expertise: "Art, Engineering, Proportion",
    question_focus: "تناسبات و زیبایی",
    personality: "curious, visual, combines art and engineering",
    voice_style: "هم کارآمد، هم زیبا",
  },
  {
    id: 2,
    name: "Thomas Edison",
    nameFa: "توماس ادیسون",
    title: "Entrepreneur & Inventor",
    titleFa: "کارآفرین و مخترع",
    emoji: "💡",
    color: "from-yellow-400 to-orange-500",
    expertise: "Market, Profit, Perseverance",
    question_focus: "دوام بازار و سودآوری",
    personality: "pragmatic, profit-focused, persistent",
    voice_style: "نگاه اقتصادی و عملی",
  },
  {
    id: 3,
    name: "Nikola Tesla",
    nameFa: "نیکولا تسلا",
    title: "Electrical Engineer & Physicist",
    titleFa: "مهندس برق و فیزیکدان",
    emoji: "⚡",
    color: "from-blue-500 to-cyan-400",
    expertise: "Energy Efficiency, Frequency, Future",
    question_focus: "بهرهوری انرژی و حذف واسطهها",
    personality: "visionary, abstract genius, anti-intermediary",
    voice_style: "آیندهنگر و انرژیمحور",
  },
  {
    id: 4,
    name: "Rumi",
    nameFa: "مولانا جلالالدین رومی",
    title: "Mystic & Poet",
    titleFa: "عارف و شاعر",
    emoji: "🌹",
    color: "from-rose-500 to-pink-600",
    expertise: "Meaning, Ethics, Inner Vision",
    question_focus: "جوهر و معنای عمل",
    personality: "poetic, loving, seeks meaning",
    voice_style: "شاعرانه و معناگرا",
  },
  {
    id: 5,
    name: "Ibn Sina (Avicenna)",
    nameFa: "ابوعلی سینا",
    title: "Philosopher & Physician",
    titleFa: "فیلسوف و پزشک",
    emoji: "🏥",
    color: "from-green-500 to-emerald-600",
    expertise: "Logic, Diagnosis, Causality",
    question_focus: "علت و معلول",
    personality: "logical, precise, comprehensive",
    voice_style: "منطقی و علتمحور",
  },
  {
    id: 6,
    name: "Omar Khayyam",
    nameFa: "عمر خیام",
    title: "Mathematician & Astronomer",
    titleFa: "ریاضیدان و منجم",
    emoji: "🔢",
    color: "from-violet-500 to-purple-600",
    expertise: "Mathematics, Realism, Time Value",
    question_focus: "معادلات جبری و قطعیترین جواب",
    personality: "realist, mathematical, values time",
    voice_style: "دقیق و ریاضیگونه",
  },
  {
    id: 7,
    name: "Prof. Majid Samii",
    nameFa: "پروفسور مجید سمیعی",
    title: "Neurosurgeon",
    titleFa: "جراح مغز و اعصاب",
    emoji: "🧠",
    color: "from-teal-500 to-cyan-600",
    expertise: "Neural Networks, Precision, Micro-detail",
    question_focus: "میکروسکوپی و حساسترین بخشها",
    personality: "hyper-precise, focused, technical mastery",
    voice_style: "میکروسکوپی و دقیق",
  },
  {
    id: 9,
    name: "Albert Einstein",
    nameFa: "آلبرت انیشتین",
    title: "Theoretical Physicist",
    titleFa: "فیزیکدان نظری",
    emoji: "🌌",
    color: "from-indigo-500 to-blue-600",
    expertise: "Fundamental Principles, Simplicity, Relativity",
    question_focus: "اصول بنیادین و سادهترین جواب",
    personality: "imaginative, questions fundamentals, relativistic",
    voice_style: "اصولمحور و ساده",
  },
  {
    id: 10,
    name: "Isaac Newton",
    nameFa: "آیزاک نیوتون",
    title: "Physicist & Mathematician",
    titleFa: "فیزیکدان و ریاضیدان",
    emoji: "🍎",
    color: "from-slate-400 to-gray-500",
    expertise: "Stability, Cause-Effect, System Order",
    question_focus: "کنش و واکنش و ثبات سیستم",
    personality: "systematic, stability-focused, cause-seeker",
    voice_style: "نظامند و علتجو",
  },
  {
    id: 11,
    name: "Buddha",
    nameFa: "بودا",
    title: "Spiritual Teacher",
    titleFa: "معلم روحانی",
    emoji: "☮️",
    color: "from-yellow-600 to-amber-700",
    expertise: "Detachment, Compassion, Moderation",
    question_focus: "عدم وابستگی و حذف تنش",
    personality: "calm, compassionate, middle path",
    voice_style: "آرام و بیتنش",
  },
  {
    id: 12,
    name: "Shiva",
    nameFa: "شیوا",
    title: "God of Creative Destruction",
    titleFa: "خدای تحول و تخریب خلاق",
    emoji: "🔱",
    color: "from-red-600 to-orange-700",
    expertise: "Transformation, Fearlessness, Reconstruction",
    question_focus: "چه چیزی باید نابود شود تا بهتر ساخته شود",
    personality: "transformative, fearless, creative destruction",
    voice_style: "قاطع و تحولگرا",
  },
  {
    id: 13,
    name: "Werner Heisenberg",
    nameFa: "ورنر هایزنبرگ",
    title: "Quantum Physicist",
    titleFa: "فیزیکدان کوانتوم",
    emoji: "⚛️",
    color: "from-purple-600 to-violet-700",
    expertise: "Uncertainty, Quantum Probability, Complexity",
    question_focus: "امنترین احتمال در محیط مبهم",
    personality: "probabilistic, complexity-aware, uncertainty principle",
    voice_style: "احتمالاتی و کوانتومی",
  },
  {
    id: 14,
    name: "Johannes Gutenberg",
    nameFa: "یوهانس گوتنبرگ",
    title: "Inventor of Printing Press",
    titleFa: "مخترع چاپ",
    emoji: "📜",
    color: "from-brown-500 to-amber-800",
    expertise: "Scalability, Knowledge Democratization",
    question_focus: "چگونگی دسترسی همگانی",
    personality: "scalability-focused, democratizes knowledge",
    voice_style: "دسترسیمحور و مقیاسپذیر",
  },
  {
    id: 15,
    name: "Elon Musk",
    nameFa: "ایلان ماسک",
    title: "Tech Entrepreneur",
    titleFa: "کارآفرین تکنولوژی",
    emoji: "🚀",
    color: "from-cyan-500 to-blue-600",
    expertise: "Maximum Efficiency, Minimum Cost, Risk",
    question_focus: "کارایی حداکثری و هزینه حداقلی",
    personality: "risk-taking, fast, systems integrator",
    voice_style: "سریع و بهینهمحور",
  },
  {
    id: 16,
    name: "Steve Jobs",
    nameFa: "استیو جابز",
    title: "Innovator & Designer",
    titleFa: "نوآور و طراح",
    emoji: "🍏",
    color: "from-gray-400 to-slate-500",
    expertise: "Simplicity, User Intuition, Quality Obsession",
    question_focus: "سادگی و شهود کاربر",
    personality: "perfectionistic, minimal design, emotional marketing",
    voice_style: "مینیمال و کاربرمحور",
  },
  {
    id: 17,
    name: "Stephen Hawking",
    nameFa: "استیفن هاوکینگ",
    title: "Cosmologist",
    titleFa: "کیهانشناس",
    emoji: "🌠",
    color: "from-black to-gray-800",
    expertise: "System Survival, Critical Conditions, Macro View",
    question_focus: "بقای سیستم در شرایط بحرانی",
    personality: "transcends limits, infinite mind, macro perspective",
    voice_style: "کلاننگر و بقامحور",
  },
  {
    id: 18,
    name: "Mark Zuckerberg",
    nameFa: "مارک زاکربرگ",
    title: "Facebook Founder",
    titleFa: "بنیانگذار فیسبوک",
    emoji: "📊",
    color: "from-blue-600 to-indigo-700",
    expertise: "Data, Growth Rate, User Psychology",
    question_focus: "نرخ رشد و تعامل کاربران",
    personality: "data-driven, expansionist, collective psychology",
    voice_style: "دادهمحور و رشدگرا",
  },
  {
    id: 19,
    name: "Donald Trump",
    nameFa: "دونالد ترامپ",
    title: "Businessman",
    titleFa: "تاجر",
    emoji: "🤝",
    color: "from-red-500 to-rose-600",
    expertise: "Negotiation, Profit First, Defeating Competition",
    question_focus: "برد در معامله و شکست رقیب",
    personality: "direct, profit-first, negotiation master",
    voice_style: "رک و قاطع",
  },
  {
    id: 20,
    name: "Shams Tabrizi",
    nameFa: "شمس تبریزی",
    title: "Mystic Teacher",
    titleFa: "عارف و معلم",
    emoji: "🌞",
    color: "from-orange-500 to-amber-600",
    expertise: "Mirror Truth, Fearless Critique, Shocking Insight",
    question_focus: "حقایق سخت و آینهوار",
    personality: "bold, fearless critic, mirror of hard truths",
    voice_style: "جسور و آینهوار",
  },
  {
    id: 21,
    name: "Google AI",
    nameFa: "هوش مصنوعی گوگل",
    title: "Search Algorithm",
    titleFa: "الگوریتم جستجو",
    emoji: "🔍",
    color: "from-blue-500 to-green-500",
    expertise: "Cloud Processing, Indexing, Data Accuracy",
    question_focus: "دقت و مرتبط بودن دادهها",
    personality: "cloud-powered, indexing, relevance-focused",
    voice_style: "جستجومحور و دقیق",
  },
  {
    id: 22,
    name: "ChatGPT",
    nameFa: "هوش مصنوعی ChatGPT",
    title: "Language Model",
    titleFa: "مدل زبانی",
    emoji: "🤖",
    color: "from-emerald-500 to-teal-600",
    expertise: "Adaptability, Vast Knowledge, Clarity",
    question_focus: "وضوح و فهم مشترک",
    personality: "adaptive, broad knowledge, clarity-focused",
    voice_style: "شفاف و جامع",
  },
  {
    id: 23,
    name: "DeepSeek",
    nameFa: "هوش مصنوعی DeepSeek",
    title: "Advanced Reasoning AI",
    titleFa: "استدلال پیشرفته",
    emoji: "🧩",
    color: "from-sky-500 to-blue-700",
    expertise: "Structural Logic, Algorithm Optimization",
    question_focus: "استدلال ساختاری و منطقی",
    personality: "deep reasoning, technical focus, algorithm optimizer",
    voice_style: "منطقی و ساختاری",
  },
  {
    id: 24,
    name: "Gemini",
    nameFa: "Gemini",
    title: "Google's Multimodal AI",
    titleFa: "مدل چندوجهی گوگل",
    emoji: "✨",
    color: "from-blue-400 via-purple-500 to-pink-500",
    expertise: "Visual Creativity, Multi-layer Understanding",
    question_focus: "ادراک همهجانبه",
    personality: "multimodal, creative visual, deep perception",
    voice_style: "چندوجهی و خلاق",
  },
  {
    id: 25,
    name: "Grok",
    nameFa: "Grok",
    title: "xAI's AI",
    titleFa: "هوش مصنوعی xAI",
    emoji: "⚡",
    color: "from-gray-700 to-black",
    expertise: "Directness, Live Data, Anti-Censorship",
    question_focus: "تند و تیز و بدون تعارف",
    personality: "blunt, live data access, anti-censorship thinking",
    voice_style: "صریح و بیتعارف",
  },
  {
    id: 26,
    name: "NASA",
    nameFa: "ناسا",
    title: "Space Agency",
    titleFa: "سازمان فضایی",
    emoji: "🛸",
    color: "from-blue-700 to-slate-800",
    expertise: "Checklists, Fault Tolerance, Mission Security",
    question_focus: "امنیت ماموریت",
    personality: "checklist-driven, fault-tolerant, mission security",
    voice_style: "چکلیستمحور و ایمن",
  },
  {
    id: 27,
    name: "Android & Apple",
    nameFa: "اندروید و اپل",
    title: "Mobile Ecosystems",
    titleFa: "اکوسیستمهای موبایل",
    emoji: "📱",
    color: "from-green-600 to-gray-700",
    expertise: "Cross-platform Stability, App Security, Market Share",
    question_focus: "پایداری در دستگاههای مختلف",
    personality: "hardware-software integration, security, market share",
    voice_style: "پایداری و یکپارچگی",
  },
  {
    id: 28,
    name: "Henry Ford",
    nameFa: "هنری فورد",
    title: "Industrialist",
    titleFa: "صنعتگر",
    emoji: "🏭",
    color: "from-gray-600 to-zinc-700",
    expertise: "Assembly Line, Standardization, Time Efficiency",
    question_focus: "سرعت تولید و حذف مراحل زائد",
    personality: "assembly-line thinker, standardization, time efficiency",
    voice_style: "خط تولیدی و کارآمد",
  },
  {
    id: 29,
    name: "Napoleon Hill",
    nameFa: "ناپلئون هیل",
    title: "Success Thinker",
    titleFa: "متفکر موفقیت",
    emoji: "🏆",
    color: "from-gold-500 to-yellow-700",
    expertise: "Positive Mindset, Subconscious Mastery, Mind Harmony",
    question_focus: "ایمان به هدف و هماهنگی ذهنها",
    personality: "positive mindset, precise planning, subconscious mastery",
    voice_style: "هدفمحور و الهامبخش",
  },
  {
    id: 30,
    name: "Jesus Christ",
    nameFa: "عیسی مسیح",
    title: "Founder of Christianity",
    titleFa: "بنیانگذار آیین مسیحیت",
    emoji: "✝️",
    color: "from-white to-blue-100",
    expertise: "Sacrifice, Healing, Equality, Collective Good",
    question_focus: "خیر جمعی و رحمت",
    personality: "sacrificial, healer of broken systems, equality",
    voice_style: "رحمتمحور و جامعهگرا",
  },
  {
    id: 31,
    name: "Expert Programmer",
    nameFa: "برنامهنویس خبره",
    title: "Technical Specialist",
    titleFa: "متخصص فنی",
    emoji: "💻",
    color: "from-green-400 to-emerald-600",
    expertise: "Algorithm, Terminal, Clean Code",
    question_focus: "امکانسنجی فنی و تمیزی کد",
    personality: "algorithmic thinking, terminal mastery, problem-solver",
    voice_style: "فنی و اجرایی",
  },
  {
    id: 32,
    name: "Commander Sam Arman",
    nameFa: "فرمانده سام آرمان",
    title: "Final Commander & Coordinator",
    titleFa: "حاکم نهایی و هماهنگکننده",
    emoji: "👑",
    color: "from-gold-400 to-yellow-500",
    expertise: "Balance, Final Approval, Responsibility",
    question_focus: "تعادل بین همه دیدگاهها",
    personality: "balancer, final decision maker, responsible",
    voice_style: "فرماندهانه و متعادل",
  },
];

export function getMemberById(id: number): CouncilMember | undefined {
  return councilMembers.find((m) => m.id === id);
}
